library(circlize)
set.seed(999)
bed = generateRandomBed()
head(bed)
bed = generateRandomBed(nr = 200, nc = 4)
head(bed)
circos.initializeWithIdeogram()
text(0, 0, "default", cex = 1)
circos.info()
circos.clear()
circos.initializeWithIdeogram()
circos.initializeWithIdeogram(species = "mm10")
circos.initializeWithIdeogram(chromosome.index=paste0("chr",c(3,5,2,8)))