data(iris)
names(iris)=c('sl','sw','pl','pw','sp')
par(mfrow=c(2,2))
hist(iris$sl)
hist(iris$sw)
hist(iris$pl)
hist(iris$pw)
options(scipen=10)
shapiro.test(iris$sl)
shapiro.test(iris$sw)
shapiro.test(iris$pl)
shapiro.test(iris$pw)
kruskal.test(sl~sp,data=iris)
kruskal.test(sw~sp,data=iris)
kruskal.test(pl~sp,data=iris)
kruskal.test(pw~sp,data=iris)
manova(cbind(sl,sw,pl,pw)~sp,data=iris)
bartlett.test(iris$sl~iris$sp)
bartlett.test(iris$sw~iris$sp)
bartlett.test(iris$pl~iris$sp)
bartlett.test(iris$pw~iris$sp)
oneway.test(sl~sp,data=iris)
oneway.test(sw~sp,data=iris)
oneway.test(pl~sp,data=iris)
oneway.test(pw~sp,data=iris)




